name: libwasmer-build

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build dynamic library for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - runtime: osx-arm64
            os: macos-12
            artifact_name: libwasmer_darwin_arm64.dylib
            make_target: capi-osx-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make ${{ matrix.make_target }}
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: |
            target/release/*.so
            target/release/*.dylib
